-- +goose Up
ALTER TABLE posts 
ALTER COLUMN title TYPE TEXT;

ALTER TABLE posts
ALTER COLUMN url TYPE TEXT;

ALTER TABLE posts
ALTER COLUMN description TYPE TEXT;


-- +goose Down
ALTER TABLE posts 
ALTER COLUMN title TYPE VARCHAR(50);

ALTER TABLE posts
ALTER COLUMN url TYPE VARCHAR(100);

ALTER TABLE posts
ALTER COLUMN description TYPE VARCHAR(100);